POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Vova",
  "email": "vova@ya.ru",
  "avatarUrl": "",
  "password": "kjsksjdfks",
  "isPro": false
}


###
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vova4@ya.ru",
  "password": "kjsksjdfks1"
}

## Отправить изображение

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< ./mocks/testAvatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
