###
GET http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZvdmFAeWEucnUiLCJuYW1lIjoiVm92YSIsImlkIjoiNjcwZDE2NDQ3ZWI1YTNmYTU3MDRmY2E1IiwiaWF0IjoxNzI5MDk1Mzc2LCJleHAiOjE3MjkyNjgxNzZ9.dnss4FRLC7tjrl0UVaHxmI1q4VzZDsUkUuuW4jk1iyc


###
GET http://localhost:4000/offers/670f427661c4eec5db8dbcf6 HTTP/1.1

###
POST http://localhost:4000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZvdmFAeWEucnUiLCJuYW1lIjoiVm92YSIsImlkIjoiNjcwZDE2NDQ3ZWI1YTNmYTU3MDRmY2E1IiwiaWF0IjoxNzI4OTExMTE1LCJleHAiOjE3MjkwODM5MTV9.skSEJw8nMWo4PRgJOdmMqa4opNr9q8TVgd-on9dOG5c

{
  "title": "test kdf lsdjfks",
  "description": "testlk jl;dgjlkfjglksfjdl;gjafl;kgjl;fjg;lsjdfgl;sjdf;s",
  "createdDate": "2024-08-10T08:11:23.283Z",
  "city": "Paris",
  "previewImage": "http://test.ru/test.png",
  "images": [
    "http://test.ru/test1.png",
    "http://test.ru/test2.png",
    "http://test.ru/test3.png",
    "http://test.ru/test4.png",
    "http://test.ru/test5.png",
    "http://test.ru/test6.png"],
  "isPremium": true,
  "rating": 3,
  "type": "house",
  "bedrooms": 2,
  "maxAdults": 2,
  "price": 1000,
  "goods": [],
  "userId": "6704f9003df41d32ec047a0e",
  "location": {
    "latitude": 48.868610000000004,
    "longitude": 2.342499
  }
}


###
PUT http://localhost:4000/offers/67069067990eba53b6c2b130 HTTP/1.1
Content-Type: application/json

{
  "title": "test111",
  "description": "test",
  "createdDate": "2024-08-10T08:11:23.283Z",
  "city": "Paris",
  "previewImage": "http://test.ru/test.png",
  "images": ["http://test.ru/test.png"],
  "isPremium": "true",
  "rating": "3",
  "type": "house",
  "bedrooms": 2,
  "maxAdults": 2,
  "price": 100,
  "goods": [],
  "location": {
    "latitude": 48.868610000000004,
    "longitude": 2.342499
  }
}

###
DELETE http://localhost:4000/offers/6704fc4a2ea09e306cc86233 HTTP/1.1


## Загрузить изображение для объявления
POST http://localhost:4000/offers/65258514a30fc6ef77c0edf7/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIiwibGFzdG5hbWUiOiJUb3JyYW5jZSIsImlkIjoiNjUyNTk2ZjdlMGE2OTEyZDI5MzA1ZGQ2IiwiaWF0IjoxNjk4Njc3ODAyLCJleHAiOjE2OTg4NTA2MDJ9.HDAdzzjP9Cnfrl9c_TdIzXdjAls2dboO_FU-bScOwmU
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="screen.png"
Content-Type: image/png

< /Users/spider_net/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:4000/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZvdmFAeWEucnUiLCJuYW1lIjoiVm92YSIsImlkIjoiNjcwZDE2NDQ3ZWI1YTNmYTU3MDRmY2E1IiwiaWF0IjoxNzI4OTExMTE1LCJleHAiOjE3MjkwODM5MTV9.skSEJw8nMWo4PRgJOdmMqa4opNr9q8TVgd-on9dOG5c


###
POST http://localhost:4000/favorites/670f427661c4eec5db8dbcf6/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZvdmFAeWEucnUiLCJuYW1lIjoiVm92YSIsImlkIjoiNjcwZDE2NDQ3ZWI1YTNmYTU3MDRmY2E1IiwiaWF0IjoxNzI5MDk1Mzc2LCJleHAiOjE3MjkyNjgxNzZ9.dnss4FRLC7tjrl0UVaHxmI1q4VzZDsUkUuuW4jk1iyc


###
GET http://localhost:4000/premium/Paris HTTP/1.1
Content-Type: application/json
