export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserController: Symbol.for('UserController'),
  UserModel: Symbol.for('UserModel'),
  OfferService: Symbol.for('OfferService'),
  OfferController: Symbol.for('OfferController'),
  OfferModel: Symbol.for('OfferModel'),
  ReviewService: Symbol.for('ReviewService'),
  ReviewController: Symbol.for('ReviewController'),
  ReviewModel: Symbol.for('ReviewModel'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
} as const;
